<HTML>
<HEAD><TITLE>CAUTION</TITLE></HEAD>
    <BODY BGCOLOR="VIOLET">

        <TABLE WIDTH="100%" BORDER="1">
<TR><TD ALIGN="CENTER">
<FONT COLOR="GREEN"><H3><A HREF="A HOME PAGE OF RAILWAY RESERVATION.php">HOME</A></H3></FONT>
</TD>
<TD ALIGN="CENTER"><FONT COLOR="GREEN"><H3><A HREF="RAIL TOUR PACKAGES.php">RAIL TOUR PACKAGES</A></H3>
</FONT></TD>
<TD ALIGN="CENTER"><FONT COLOR="GREEN"><H3><A HREF="LOYALITYPROGRAMMES.php">LOYALITY PROGRAMMES</A></H3>
</FONT>
</TD>
<TD ALIGN="CENTER"><FONT COLOR="GREEN"><H3><A HREF="ABOUT INDIAN RAILWAYS.php">ABOUT INDIAN RAILWAYS</A></H3></FONT></TD><TD ALIGN="CENTER">
<FONT COLOR="GREEN"><H3><A HREF="FIND TRAINS.HTML">RESERVATION</A></H3>
</FONT>
</TD>
<TD ALIGN="CENTER"><FONT COLOR="GREEN"><H3>
<A HREF="NEWS.php">NEWS</A></H3></FONT>
</TD>
<TD ALIGN="CENTER"><FONT COLOR="GREEN"><H3>
<A HREF="CONTACT US.php">CONTACT US</A></H3></FONT>
</TD>
</TABLE>

    <CENTER>
<TABLE WIDTH="AUTO" BGCOLOR="SILVER">
        <TR><TD ALIGN="CENTER"><IMG SRC="images/ARSH.png"WIDTH="650PX"HEIGHT="200PX"/></TD></TR>
    <TR><TD ALIGN="CENTER"><FONT COLOR="RED" SIZE="5"><U><B>CAUTION</B></U></FONT></TD></TR>
    <TR>
    <TD> <U><FONT COLOR="BLACK">IF YOU HAVE LEFT ANY FIELD THEN YOUR REGISTRATION WILL BE CANCELLED AUTOMATICALLY </FONT></U></TD></TR>
        <TR><TD><UL><LI>FOR CONFIRM-PRESS "OK" BUTTON </LI>
            <LI>FOR REFFILING FORM PRESS "CANCEL" BUTTON</LI>
                
            </UL></TR>
            <TR>
            
            <TD ALIGN="CENTER">
                <A HREF="CONGRATULATION.php"><INPUT TYPE="BUTTON"VALUE="OK" STYLE="HEIGHT:30PX"></A>&nbsp&nbsp&nbsp&nbsp
                    <a href="FIND%20TRAINS.php"><input type="button"value="CANCEL" style="height:30px"></a>
                
                
                
                </TD></TR>
    
        
        </TABLE></CENTER>
    
    </BODY>
</HTML>